apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-custom-config-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: basic-config
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: basic-config
          configMap:
            name: basic-config

