apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar
spec:
  containers:
  - name: nginx-web
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: nginx-proxy
    image: nginx:1.14.2
    ports:
    - containerPort: 8080