apiVersion: v1
kind: Secret
metadata:
 name: nginx-ssl
type: Opaque
data:
 snakeoil.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2VSSFBvT1NseGtld0kKdkNYMm9jR1pCclp4RytOT2Vwb0JqYkVQMWd2aEJRN3hRSzY5Y1ZudWJLcEozR0JTQmVMdDBybU05UTlvRnV2WQowelorTTJveDN3MlUweVdNVHZXdEdJVktSWHc4Ui9rVHlSeU9CamZpSGdGdTVRbk1lK2lEbStzbllYY0xORXZMCnhCS2h5SXNiL1c5SUM5ekhzZTRiZ3JwU1JybkoyZmFqZWo1RWZaeVVtMjg2L2pBVlpHaXNEMm44R0RobEdIZkYKTGh1K0xleVVnMWo3Y0w0SUJBMk9xYm4yaDJYZkRFeUcvWmU1UzE4QllKeFZSNTJaNE9pMnRXQ3B0RTFlUm9CbApoTjN4N0I3NnB1cU9UL29oelQ1Y0ltWEZ2YkVlcFd5M0J1eWV0TEp6bzB5ZFJmWTVMaE1SY0dUNUFhdlZhYnF0ClJMci9KUnUzQWdNQkFBRUNnZ0VBY0QyL3JidU1ScnprRmpYSS9xWXM5R2VzVDM4bHIyeUhkLzZTeWRaVlNsb2EKQk1LSXFsV1BIK1gweHJrQm5tb0tTL3VjRi9sYjJjZ1hyd2ZycDRpekVYZE0zSFQ2TmcxeGNqYm5vSXF5MXRWOApNYW41RkVnWXJjWDE0ajJRdTNKTXJibVFCYmU3Z3ppdFlHOUhmM0VJSnV1UFZoc0RrcVAvWjRkSXVEenNXZGVhCjYvODF4NG1rbnF5ZTZWV3ZmR0VranhuRUV4QS9NZnNPNG1uQkRGdHRyTEtjTy8xTXhFMW5Caml6SDdkaitaSkwKanNiYUdqaEttcURhb2RSYW1jdlVIaGNuZU9jTjlIMHFzY2hncm9MdzlkSEZUN3Y3MURxVWlXUnBrUWo5V1V6WQpqMktkL0pnZGNzSmUyU2RMY2R3cFhlcGtyNHhxNDR2dDZoYkkvdXRZZ1FLQmdRRExTeUVGby95YVpGbGZzc0l3CmpmUXlDOERPaS8wVFFBRWg2VTFOZGtxcGFQR3huWllKMkFFTk1hM1oyMmZxY0ZSTnZBSG43aUp0V2ZBWEQrMG0Kei9xQjNKMThETldIT1FkT3VRZEZDSEFxQlRrOVZNVjhqazZ4bzdSWCtXSlh4NmkvNVFrZkY5ZjRxUk5oQ0lKUgo1aEtMdGp1anQyRVBSTXRFVWhBT2VONy9Wd0tCZ1FESFRPRlRIY0kyRDVtUzR3TitKVzBEZWt6Wll4cjlUSVFSCnQ1RG1JVGdWeTNQK1lPQVFnT2FwT3FCcDJPYzIzU1FxZEV2WVU1R0daY2EvSWs1Z2krN09zeXE3ay9kbXBvNmMKMVBVVnZYU1o0ckovaUlTd0FZMTJDZWptRGtNbEVVUVNBQ255Z0MrY0VMd2hKTEt5TC9nQnFvVzREQjNreS9yQgp6ZlNJY3VmcW9RS0JnRDBpK2VwVlY3a2lwcElXRXpwQTVvaEthcEJ6SHdlei91TXc0MU9CV0pDOEE3dVRsYlNlCkppck9udWJlaWREQ09VZ3JXek5odFM3SGxtR0pJNXZCZmllaHJpYkpRVW5xUjUxUUhiU1FCaE5OQU5yRjdLSTUKdGNiTVlZYjNjN0RNVlo1b0JhYzVKM1ViZTcxNXJwOXNublV2dDUzVG56ZlZTMy9mWWY3SU1OLy9Bb0dCQUpubwo2ajJZeHFtZkpIZEY3eVdVMjNvTEVadnpxQjBpNFA4WnBzSEJ0NkZGTEQrdktubzBRVzFCQkM2WnZmMGxqRTlvCjNrV2lTOGpoZ2ptSzBjSkhibFdjRVkwb2VLK0NRcklrMTF4Qm9mRlJHNDNYckxpTGltWTB3dkllNDRXVnJ0N0QKMTZFWmt5clAxYWsyd1BWUWpCTWxUL3pSQnFqeFNhWXZXZitoMVMzaEFvR0FWUHZrNHlaTnlvd3BHTmozcW16RgoxT1MzNktkYjBXUVp0ZVpQRDB3OWhSM1FiY2d1RWdlcTJpY2FFRUhUaUEzVlpieTNaWmZ2ZkppTG83dTVkUDRhCk4xT2IxZEJHVlAzR3RPd2NCaUQ3ZlZIUG1WaXJnYStaSklkNVEycVc4Q1lWbllveklIS01FL1pmTEtad1IraFUKOWlaTFVCaFRZaW9zQkNwOW9rQWp1QW89Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
 snakeoil.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyakNDQVphZ0F3SUJBZ0lKQU9US1FDMHhzWHpUTUEwR0NTcUdTSWIzRFFFQkN3VUFNQTh4RFRBTEJnTlYKQkFNTUJHcDFibTh3SGhjTk1UWXdOakEwTVRVMU1URTRXaGNOTWpZd05qQXlNVFUxTVRFNFdqQVBNUTB3Q3dZRApWUVFEREFScWRXNXZNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW5rUno2RGtwCmNaSHNDTHdsOXFIQm1RYTJjUnZqVG5xYUFZMnhEOVlMNFFVTzhVQ3V2WEZaN215cVNkeGdVZ1hpN2RLNWpQVVAKYUJicjJOTTJmak5xTWQ4TmxOTWxqRTcxclJpRlNrVjhQRWY1RThrY2pnWTM0aDRCYnVVSnpIdm9nNXZySjJGMwpDelJMeThRU29jaUxHLzF2U0F2Y3g3SHVHNEs2VWthNXlkbjJvM28rUkgyY2xKdHZPdjR3RldSb3JBOXAvQmc0ClpSaDN4UzRidmkzc2xJTlkrM0MrQ0FRTmpxbTU5b2RsM3d4TWh2Mlh1VXRmQVdDY1ZVZWRtZURvdHJWZ3FiUk4KWGthQVpZVGQ4ZXdlK3FicWprLzZJYzArWENKbHhiMnhIcVZzdHdic25yU3ljNk5NblVYMk9TNFRFWEJrK1FHcgoxV202clVTNi95VWJ0d0lEQVFBQm93MHdDekFKQmdOVkhSTUVBakFBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQlJmMks0eDFRQkYxdVBRM0czc2VJUnBwb1d1TlpDN0h6cjZ6N1FxTHJ6L2NLRnZML2UrdlE0SThkVHpPOHkKdHE2WmRESG9QQlRYdFV0MTBndDd0TkEzMVFsRkcwd3B4aWc4ditsOUNxOXh4Y2NtRjZuT1RUUm9GTTRwRHlDNgozdFQ0cWkrYUFQY0QxQUxHa2NzVjBWMXNLR1Z4a1BpVmYzaUtGajNMWWRnbkRoUHRyb3BlMk9ENjBTMkFhZE1uCjVYUDJNZlpERmhmOHNzMjJQUGdSV3Z5T3BRd1RHaHAzYXBiQURUdGFBQys3RlZVSTRoSVp2WnZUa0Vteklld3AKbUtxak1BYmdmYjNaNFZKamptZUFLL2pmc0hPVmtaREJ0Um04WWFWRWNjYTJCVGNubE83bjVTalBPYm52eWs5bgpzR1lscmpOMUVHbmFiU05qTHo2c0dTQ0wKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: arwthomasm/pacman:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
        - mountPath: /etc/nginx/ssl
          name: nginx-ssl
          readOnly: true
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
---
apiVersion: v1
kind: Service
metadata:
  name: pacman-svc
spec:
  type: NodePort
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: http
  selector:
    app: pacman